spring:
  mail:
    host: localhost
    port: 1025
    test-connection: false
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: test-notification-service
      auto-offset-reset: earliest

app:
  email:
    test-mode: true

logging:
  level:
    com.notificationservice: DEBUG
    org.springframework.kafka: DEBUG