spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_test
    username: postgres
    password: password

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
    contexts: test

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.userservice: DEBUG
    org.hibernate.SQL: DEBUG